language: node_js
node_js:
  - stable
cache:
  yarn: true

script: yarn test

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  message: "Deploying v$TRAVIS_TAG to Firebase"

# 1/nxfLylxfBaRa2fXZLPEUSGpwqen13wxJG9io_zjRS9g
