language: node_js
node_js:
  - stable

cache:
  yarn: true

script: yarn test -- --single-run

before_deploy: yarn build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  message: Deploying v$TRAVIS_TAG to Firebase
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_failure: change
    on_success: change

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
